### ISSUE TITLE
port organization and user console commands to sf4

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/standard#1]
port organization and user console commands to sf4

**Comment by stefan-kamsker** [comment]
hmm, habe (noch) keinen besseren weg gefunden als es als service zu registrieren
dann gehen sie wieder

was meinst du dazu
https://github.com/united-cms/CoreBundle/commit/68ce76911cf55a0616ff2e5c89fdf21d1664769c

mit autoloading habe ich es mit sf4 noch nicht hinbekommen

**Comment by franzwilding** [comment]
Thats fine, however you should also let the commands extend from Command instead of ContainerAwareCommand and inject all dependencies via service dependency injection (https://symfony.com/doc/current/console/commands_as_services.html)

**Comment by stefan-kamsker** [comment]
sorry for the german :), i changed that
